models:
  - type: main
    engine: openai
    model: openai/gpt-oss-20b
    parameters:
      base_url: https://api.groq.com/openai/v1
      api_key: unused

colang_version: "1.0"

rails:
  input:
    flows:
      - check prompt guard
      - check jailbreak
      - check prompt injection
      - check off topic
